name:                sndr
version:             0.1.0.0
github:              "githubuser/sndr"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2022 Author name here"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/sndr#readme>

dependencies:
  - aeson
  - base >= 4.7 && < 5
  - bytestring
  - monad-logger
  - mtl
  - path-pieces
  - persistent
  - persistent-postgresql
  - safe
  - servant-server
  - text
  - transformers
  - uuid
  - wai
  - wai-extra
  - warp
  - servant-errors
  - servant

library:
  source-dirs: src

executables:
  sndr-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - sndr

tests:
  sndr-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - sndr
    - servant-client
    - hspec
    - lens
    - unordered-containers
    - hspec-wai
    - servant-quickcheck
    - aeson
    - aeson-lens
    - http-types
    - base-compat-batteries
    - http-client
